/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#define ACCESSIBILITY 1
#define DETECT_WEBSHELL_LEAKS 1
#define D_INO d_ino
#define FUNCPROTO 15
#define HAVE_CPP_2BYTE_WCHAR_T 1
#define HAVE_CPP_ACCESS_CHANGING_USING 1
#define HAVE_CPP_AMBIGUITY_RESOLVING_USING 1
#define HAVE_CPP_DYNAMIC_CAST_TO_VOID_PTR 1
#define HAVE_CPP_EXPLICIT 1
#define HAVE_CPP_MODERN_SPECIALIZE_TEMPLATE_SYNTAX 1
#define HAVE_CPP_NAMESPACE_STD 1
#define HAVE_CPP_NEW_CASTS 1
#define HAVE_CPP_PARTIAL_SPECIALIZATION 1
#define HAVE_CPP_SPECIALIZATION 1
#define HAVE_CPP_UNAMBIGUOUS_STD_NOTEQUAL 1
#define HAVE_DIRENT_H 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_GETOPT_H 1
#define HAVE_GNU_GET_LIBC_VERSION 1
#define HAVE_GNU_LIBC_VERSION_H 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_INT16_T 1
#define HAVE_INT32_T 1
#define HAVE_INT64_T 1
#define HAVE_IOS_BIN 1
#define HAVE_IOS_BINARY 1
#define HAVE_LCHOWN 1
#define HAVE_LIBDL 1
#define HAVE_LIBM 1
#define HAVE_LOCALTIME_R 1
#define HAVE_MBRTOWC 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_NL_LANGINFO 1
#define HAVE_NL_TYPES_H 1
#define HAVE_RANDOM 1
#define HAVE_RES_NINIT 1
#define HAVE_RINT 1
#define HAVE_SNPRINTF 1
#define HAVE_STATVFS 1
#define HAVE_STRERROR 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_SYS_STATFS_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_VFS_H 1
#define HAVE_UINT 1
#define HAVE_UNAME_US_DOMAINNAME_FIELD 1
#define HAVE_UNISTD_H 1
#define HAVE_WCRTOMB 1
#define HAVE_X11_XKBLIB_H 1
#define HAVE_XSHM 1
#define IBMBIDI 1
#define INCLUDE_XUL 1
#define JS_THREADSAFE 1
#define MOZ_DEFAULT_TOOLKIT "gtk"
#define MOZ_DEMANGLE_SYMBOLS 1
#define MOZ_DLL_SUFFIX ".so"
#define MOZ_ENABLE_XREMOTE 1
#define MOZ_LOGGING 1
#define MOZ_MATHML 1
#define MOZ_REFLOW_PERF 1
#define MOZ_REFLOW_PERF_DSP 1
#define MOZ_USER_DIR ".mozilla"
#define MOZ_WIDGET_GTK 1
#define MOZ_X11 1
#define MOZ_XUL 1
#define NEED_CPP_UNUSED_IMPLEMENTATIONS 1
#define NS_MT_SUPPORTED 1
#define NS_PRINT_PREVIEW 1
#define STDC_HEADERS 1
#define UNIX_ASYNC_DNS 1
#define USE_IMG2 1
#define _REENTRANT 1
/* #define XP_UNIX 1 */
/* #define _POSIX_SOURCE 1 */
/* #define _GNU_SOURCE 1 */
/* #define _SVID_SOURCE 1 */
