#! /bin/sh
ant clean
cd jni
/Users/johns/Desktop/Android-tests-current/android_tools/android-ndk-r7/ndk-build
cd ..
ant debug
echo
echo "installing on JohnS Acer Iconia A500"
adb -s 388924841bf5497 install -r ./bin/FreeWRL-debug-unaligned.apk
