/* A header simply containing all VRML types; this is needed sometimes. */

SF_TYPE(SFBool, sfbool, Bool)
MF_TYPE(MFBool, mfbool, Bool)
SF_TYPE(SFColor, sfcolor, Color)
MF_TYPE(MFColor, mfcolor, Color)
SF_TYPE(SFColorRGBA, sfcolorrgba, ColorRGBA)
MF_TYPE(MFColorRGBA, mfcolorrgba, ColorRGBA)
SF_TYPE(SFFloat, sffloat, Float)
MF_TYPE(MFFloat, mffloat, Float)
SF_TYPE(SFImage, sfimage, Image)
SF_TYPE(SFInt32, sfint32, Int32)
MF_TYPE(MFInt32, mfint32, Int32)
SF_TYPE(SFNode, sfnode, Node)
MF_TYPE(MFNode, mfnode, Node)
SF_TYPE(SFRotation, sfrotation, Rotation)
MF_TYPE(MFRotation, mfrotation, Rotation)
SF_TYPE(SFString, sfstring, String)
MF_TYPE(MFString, mfstring, String)
SF_TYPE(SFTime, sftime, Time)
MF_TYPE(MFTime, mftime, Time)
SF_TYPE(SFVec2f, sfvec2f, Vec2f)
MF_TYPE(MFVec2f, mfvec2f, Vec2f)
SF_TYPE(SFVec3f, sfvec3f, Vec3f)
MF_TYPE(MFVec3f, mfvec3f, Vec3f)
