/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class FreeWRL */

#ifdef IMPLEMENT_FreeWRL
#define _implementing_FreeWRL
#endif /* IMPLEMENT_FreeWRL */
#define IMPLEMENT_FreeWRL
#include "FreeWRL.h"

#ifndef UNUSED_FreeWRL_count
JRIFieldID FAR fieldID_FreeWRL_count = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_FreeWRL_count(JRIEnv* env, struct FreeWRL* obj) {
	if (fieldID_FreeWRL_count == JRIUninitialized) {
		assert(!"Forgot to call use_FreeWRL(env) before accessing field count I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_FreeWRL_count);
}
JRI_PUBLIC_API(void)
set_FreeWRL_count(JRIEnv* env, struct FreeWRL* obj, jint v) {
	if (fieldID_FreeWRL_count == JRIUninitialized) {
		assert(!"Forgot to call use_FreeWRL(env) before accessing field count I");
	}
	JRI_SetFieldInt(env, obj, fieldID_FreeWRL_count, v);
}
#endif /* DEBUG */
#endif /* UNUSED_FreeWRL_count */

#ifndef UNUSED_FreeWRL_fact
JRIMethodID FAR methodID_FreeWRL_fact = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
FreeWRL_fact(JRIEnv* env, struct java_lang_Class* clazz, jint a) {
	if (methodID_FreeWRL_fact == JRIUninitialized) {
		assert(!"Forgot to call use_FreeWRL(env) before calling method fact (I)I");
	}
	return (jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_FreeWRL_fact, a);
}
#endif /* DEBUG */
#endif /* UNUSED_FreeWRL_fact */

#ifndef UNUSED_FreeWRL_printToStdout
JRIMethodID FAR methodID_FreeWRL_printToStdout = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
FreeWRL_printToStdout(JRIEnv* env, struct FreeWRL* self, struct java_lang_String *a) {
	if (methodID_FreeWRL_printToStdout == JRIUninitialized) {
		assert(!"Forgot to call use_FreeWRL(env) before calling method printToStdout (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_FreeWRL_printToStdout, a);
}
#endif /* DEBUG */
#endif /* UNUSED_FreeWRL_printToStdout */

#ifndef UNUSED_FreeWRL_doit
JRIMethodID FAR methodID_FreeWRL_doit = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
FreeWRL_doit(JRIEnv* env, struct FreeWRL* self, struct java_lang_String *a) {
	if (methodID_FreeWRL_doit == JRIUninitialized) {
		assert(!"Forgot to call use_FreeWRL(env) before calling method doit (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_FreeWRL_doit, a);
}
#endif /* DEBUG */
#endif /* UNUSED_FreeWRL_doit */

#ifndef UNUSED_FreeWRL_new
JRIMethodID FAR methodID_FreeWRL_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct FreeWRL*)
FreeWRL_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_FreeWRL_new == JRIUninitialized) {
		assert(!"Forgot to call use_FreeWRL(env) before calling method <init> ()V");
	}
	return (struct FreeWRL*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_FreeWRL_new);
}
#endif /* DEBUG */
#endif /* UNUSED_FreeWRL_new */

#ifndef UNUSED_use_FreeWRL

static jglobal _globalclass_FreeWRL = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_FreeWRL(JRIEnv* env)
{
	if (_globalclass_FreeWRL == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_FreeWRL);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_FreeWRL);
			return NULL;
		}
		use_FreeWRL_count(env, clazz);
		use_FreeWRL_fact(env, clazz);
		use_FreeWRL_printToStdout(env, clazz);
		use_FreeWRL_doit(env, clazz);
		use_FreeWRL_new(env, clazz);
		_globalclass_FreeWRL = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return JRI_GetGlobalRef(env, _globalclass_FreeWRL);
	}
}

JRI_PUBLIC_API(void)
unuse_FreeWRL(JRIEnv* env)
{
	if (_globalclass_FreeWRL != NULL) {
		struct java_lang_Class* clazz = JRI_GetGlobalRef(env, _globalclass_FreeWRL);
		unuse_FreeWRL_count(env, clazz);
		unuse_FreeWRL_fact(env, clazz);
		unuse_FreeWRL_printToStdout(env, clazz);
		unuse_FreeWRL_doit(env, clazz);
		unuse_FreeWRL_new(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_FreeWRL);
		_globalclass_FreeWRL = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_FreeWRL */

#ifdef _implementing_FreeWRL

JRI_PUBLIC_API(struct java_lang_Class*)
register_FreeWRL(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"printToStdout(Ljava/lang/String;)V",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_FreeWRL_printToStdout,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_FreeWRL);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_FreeWRL);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_FreeWRL(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_FreeWRL(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_FreeWRL);
	JRI_UnregisterNatives(env, clazz);
	unuse_FreeWRL(env);
}

#endif /* _implementing_FreeWRL */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "FreeWRL/printToStdout(Ljava/lang/String;)V", Java_FreeWRL_printToStdout_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_FreeWRL_printToStdout_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_FreeWRL_printToStdout(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

#endif /* NO_JDK */

