/*
=INSERT_TEMPLATE_HERE=

$Id$

Proximity sensor macro.

*/

#ifndef __FREEWRL_SCENEGRAPH_PROGRAMMABLESHADERS_H__
#define __FREEWRL_SCENEGRAPH_PROGRAMMABLESHADERS_H__

extern GLuint globalCurrentShader;

#endif /* __FREEWRL_SCENEGRAPH_PROGRAMMABLESHADERS_H__ */
