Document: freewrl
Title: Debian freewrl Manual
Author: <insert document author here>
Abstract: This manual describes what freewrl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freewrl/freewrl.sgml.gz

Format: postscript
Files: /usr/share/doc/freewrl/freewrl.ps.gz

Format: text
Files: /usr/share/doc/freewrl/freewrl.text.gz

Format: HTML
Index: /usr/share/doc/freewrl/html/index.html
Files: /usr/share/doc/freewrl/html/*.html

  
