//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstSFRotation extends ConstField {
    float axisX;
    float axisY;
    float axisZ;
    float angle;

    public ConstSFRotation() {
    }
    public ConstSFRotation(float axisX, float axisY, float axisZ, float angle) {
        this.axisX = axisX;
        this.axisY = axisY;
        this.axisZ = axisZ;
        this.angle = angle;
    }

    public void getValue(float[] values) {
        __updateRead();
        values[0] = axisX;
        values[1] = axisY;
        values[2] = axisZ;
        values[3] = angle;
    }

    public String toString() {
        __updateRead();
        return ""+axisX+" "+axisY+" "+axisZ+" "+angle;
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        axisX = Float.parseFloat(in.readUTF());
        axisY = Float.parseFloat(in.readUTF());
        axisZ = Float.parseFloat(in.readUTF());
        angle = Float.parseFloat(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(""+axisX);
        out.writeUTF(""+axisY);
        out.writeUTF(""+axisZ);
        out.writeUTF(""+angle);
    }
}