// GENERATED BY genfields.pl. DO NOT EDIT!
package vrml.field;
import vrml.*;
import java.util.*;

public class ConstSFInt32 extends ConstField {
int v;
public ConstSFInt32(int val) { v=val;}
public ConstSFInt32(String s) throws Exception {
		;
		if(s == null) {
			v = 0;; return;
		}
		s = s.trim();
		
	s = s.trim();
	v = new Integer(s).intValue();

	}public int getValue() {return v;}
public String toString() {return new Integer(v).toString();}public Object clone() {ConstSFInt32 _x = new ConstSFInt32(v); return _x;}}