//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstSFBool extends ConstField {
    boolean value;

    public ConstSFBool() {
    }
    public ConstSFBool(boolean value) {
        this.value = value;
    }

    public boolean getValue() {
        __updateRead();
        return value;
    }

    public String toString() {
        __updateRead();
        return value ? "TRUE" : "FALSE";
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        value = in.readBoolean();
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeBoolean(value);
    }
}