//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstMFTime extends ConstMField {
    public ConstMFTime() {
    }

    public ConstMFTime(double[] value) {
        this(value.length, value);
    }

    public ConstMFTime(int size, double[] value) {
        for (int i = 0; i < size; i++)	
            __vect.addElement(new ConstSFTime(value[i]));
    }
	
    public void getValue(double[] value) {
        __updateRead();
        int size = __vect.size();
        for (int i = 0; i < size; i++) {
            ConstSFTime sfTime = (ConstSFTime) __vect.elementAt(i);
            value[i] = sfTime.value;
        }
    }

    public double get1Value(int index) {
        __update1Read(index);
        return ((ConstSFTime) __vect.elementAt(index)).getValue();
    }

    public String toString() {
        __updateRead();
        StringBuffer sb = new StringBuffer("[");
        int size = __vect.size();
        for (int i = 0; i < size; i++) {
            if (i > 0) sb.append(", ");
            sb.append(__vect.elementAt(i));
        }
        return sb.append("]").toString();
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        __vect.clear();
        int len = in.readInt();
        for (int i = 0; i < len; i++) {
            ConstSFTime sf = new ConstSFTime();
            sf.__fromPerl(in);
            __vect.addElement(sf);
        }
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        StringBuffer sb = new StringBuffer("");
        int size = __vect.size();
	out.writeInt(size);
        for (int i = 0; i < size; i++)
            ((ConstSFTime) __vect.elementAt(i)).__toPerl(out);
    }
}