//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstSFNode extends ConstField {
    BaseNode node;

    public ConstSFNode() {
    }
    public ConstSFNode(BaseNode node) {
        this.node = node;
    }

    public BaseNode getValue() {
        __updateRead();
        return node;
    }

    public String toString() {
        __updateRead();
        return FWHelper.nodeToString(node);
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        node = new vrml.node.Node(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(node._get_nodeid());
    }
}