//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;

public class ConstSFNode extends ConstField {
    BaseNode node;

    public ConstSFNode() {
    }
    public ConstSFNode(BaseNode node) {
        this.node = node;
    }

    public BaseNode getValue() {
        __updateRead();
        return node;
    }

    public String toString() {
        __updateRead();
        return FWHelper.nodeToString(node);
    }

    public void __fromPerl(String str) {
        node = new vrml.node.Node(str);
    }

    public String __toPerl() {
        return node._get_nodeid();;
    }
}