//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstSFFloat extends ConstField {
    float f;

    public ConstSFFloat() {
    }
    public ConstSFFloat(float f) {
        this.f = f;
    }

    public float getValue() {
        __updateRead();
        return f;
    }

    public String toString() {
        __updateRead();
        return String.valueOf(f);
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        f = Float.parseFloat(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(""+f);
    }
}