//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstSFColor extends ConstField {
    float red;
    float green;
    float blue;

    public ConstSFColor() {
    }
    public ConstSFColor(float red, float green, float blue) {
        this.red = red;
        this.green = green;
        this.blue = blue;
    }

    public void getValue(float[] values) {
        __updateRead();
        values[0] = red;
        values[1] = green;
        values[2] = blue;
    }

    public float getRed() {
        __updateRead();
        return red;
    }

    public float getGreen() {
        __updateRead();
        return green;
    }

    public float getBlue() {
        __updateRead();
        return blue;
    }

    public String toString() {
        __updateRead();
        return ""+red+" "+green+" "+blue;
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        red = Float.parseFloat(in.readUTF());
        green = Float.parseFloat(in.readUTF()); 
        blue = Float.parseFloat(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(""+red);
        out.writeUTF(""+green); 
        out.writeUTF(""+blue);
    }
}