//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class ConstSFVec3f extends ConstField {
    float x;
    float y;
    float z;

    public ConstSFVec3f() {
    }
    public ConstSFVec3f(float x, float y, float z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }

    public void getValue(float[] values) {
        __updateRead();
        values[0] = x;
        values[1] = y;
        values[2] = z;
    }

    public float getX() {
        __updateRead();
        return x;
    }

    public float getY() {
        __updateRead();
        return y;
    }

    public float getZ() {
        __updateRead();
        return z;
    }

    public String toString() {
        __updateRead();
        return ""+x+" "+y+" "+z;
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        x = Float.parseFloat(in.readUTF());
        y = Float.parseFloat(in.readUTF());
        z = Float.parseFloat(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(""+x);
        out.writeUTF(""+y);
        out.writeUTF(""+z);
    }
}