//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class SFBool extends Field {
    boolean value;

    public SFBool() {
    }
    public SFBool(boolean value) {
        this.value = value;
    }

    public boolean getValue() {
        __updateRead();
        return value;
    }

    public void setValue(boolean value) {
        this.value = value;
        __updateWrite();
    }

    public void setValue(ConstSFBool sfBool) {
        sfBool.__updateRead();
        value = sfBool.value;
        __updateWrite();
    }

    public void setValue(SFBool sfBool) {
        sfBool.__updateRead();
        value = sfBool.value;
        __updateWrite();
    }

    public String toString() {
        __updateRead();
        return value ? "TRUE" : "FALSE";
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        value = in.readBoolean();
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeBoolean(value);
    }
}