//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class SFInt32 extends Field {
    int value;

    public SFInt32() {
    }
    public SFInt32(int value) {
        this.value = value;
    }

    public int getValue() {
        __updateRead();
        return value;
    }

    public void setValue(int value) {
        this.value = value;
        __updateWrite();
    }

    public void setValue(ConstSFInt32 sfInt32) {
        sfInt32.__updateRead();
        value = sfInt32.value;
        __updateWrite();
    }

    public void setValue(SFInt32 sfInt32) {
        sfInt32.__updateRead();
        value = sfInt32.value;
        __updateWrite();
    }

    public String toString() {
        __updateRead();
        return String.valueOf(value);
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        value = in.readInt();
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeInt(value);
    }
}