//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class SFNode extends Field {
    BaseNode node;

    public SFNode() {
    }
    public SFNode(BaseNode node) {
        this.node = node;
    }

    public BaseNode getValue() {
        __updateRead();
        return node;
    }

    public void setValue(BaseNode node) {
        this.node = node;
        __updateWrite();
    }

    public void setValue(ConstSFNode sfNode) {
        sfNode.__updateRead();
        node = sfNode.node;
        __updateWrite();
    }

    public void setValue(SFNode sfNode) {
        sfNode.__updateRead();
        node = sfNode.node;
        __updateWrite();
    }

    public String toString() {
        __updateRead();
        return FWHelper.nodeToString(node);
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        node = new vrml.node.Node(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(node._get_nodeid());
    }
}