//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

public class SFTime extends Field {
    double value;

    public SFTime() {
    }
    public SFTime(double value) {
        this.value = value;
    }

    public double getValue() {
        __updateRead();
        return value;
    }

    public void setValue(double value) {
        this.value = value;
        __updateWrite();
    }

    public void setValue(ConstSFTime sfTime) {
        sfTime.__updateRead();
        value = sfTime.value;
        __updateWrite();
    }

    public void setValue(SFTime sfTime) {
        sfTime.__updateRead();
        value = sfTime.value;
        __updateWrite();
    }

    public String toString() {
        __updateRead();
        return String.valueOf(value);
    }

    public void __fromPerl(DataInputStream in)  throws IOException {
        value = Double.parseDouble(in.readUTF());
    }

    public void __toPerl(DataOutputStream out)  throws IOException {
        out.writeUTF(""+value);
    }
}